# Project information
site_name: Solidity Resources
site_url: https://github.com/RossJH/Solidity.git
site_author: Ross Hardingham

# Repository
repo_name: Solidity
repo_url: https://github.com/RossJH/Solidity
edit_uri: edit/master/documentation
docs_dir: documentation

# Navigation
nav:
  - README.md:
      - Overview: steps/Dancers.md
      - Test: steps/Dancers.md
      - test: steps/people.md
      - test: steps/checks.md
  - YouTube-Channels:
      - Learn Solidity, Blockchain, and Smart Contracts in a Free 16-Hour Course: Info/youtube.md
      - Solidity Tutorial – How to Create NFTs with Hardhat: video/youtube.md
      - test: video/test-1.md
      - test: video/test.md
  - Tools/Libraries:
      - Truffle: Info/youtube.md
      - Remix IDE: Info/youtube.md
      - Hardhat: Info/test-1.md
      - test: Info/test.md
  - Projects:
      - Your first contract: Info/youtube.md
      - NFT contract: Info/youtube.md
      - Hardhat: Info/test-1.md
      - test: Info/test.md

## DO NOT CHANGE BELOW THIS LINE

# Copyright
# TBD

# Theme
theme:
  name: material
  custom_dir: overrides
  font:
    text: IBM Plex Sans
    code: IBM Plex Mono
  icon:
    logo: material/ethereum
  features:
    # - navigation.tabs
    - navigation.instant
    - navigation.expand
    # - navigation.tracking
    #  - navigation.tabs
    # - navigation.tabs.sticky
    # - navigation.sections
    # - navigation.expand
    # - navigation.indexes
    # - navigation.top
    - search.suggest
    - search.share
    - header.autohide
  palette:
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to light mode
# Plugins
plugins:
  - search

# Analytics
extra:
  analytics:
    provider: google
    property: G-FHV0KJELZ3
  consent:
    title: Cookie consent
    description:
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/
    - icon: fontawesome/brands/medium
      link: https://twitter.com/
  generator: false

# Customization
# TBD

copyright: A journey to learn solidity in 2022 and document the resources accumulated along the way.

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
